### ISSUE TITLE
Need demo!

### ISSUE THREAD

**Issue by Thundros** [JuniorDjjr/Unity-Procedural-Stochastic-Texture-Terrain-Shader#1]
Can you at least put up an actual demo utilizing this please? Some of us are actually still a bit new to Unity & would like to see how this demo functions.

**Comment by JuniorDjjr** [comment]
Put into your Assets folder and just change your terrain material by `StochasticTerrain.mat` (Universal Render Pipeline only for now). You change it into your terrain settings. Nothing special here.

**Comment by tfalmeida91** [comment]
Shader error in 'Universal Render Pipeline/Terrain/StochasticTerrain': Couldn't open include file 'Packages/com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitDepthNormalsPass.hlsl'

Shader error in 'Hidden/Universal Render Pipeline/Terrain/StochasticTerrain (Add Pass)': Couldn't open include file 'Packages/com.unity.render-pipelines.universal/ShaderLibrary/DBuffer.hlsl'. at Assets/StochasticTerrainPasses.hlsl
