### ISSUE TITLE
Possible missing files?

### ISSUE THREAD

**Issue by tfalmeida91** [JuniorDjjr/Unity-Procedural-Stochastic-Texture-Terrain-Shader#3]
Shader error in 'Universal Render Pipeline/Terrain/StochasticTerrain': Couldn't open include file 'Packages/com.unity.render-pipelines.universal/Shaders/Terrain/TerrainLitDepthNormalsPass.hlsl'

Shader error in 'Hidden/Universal Render Pipeline/Terrain/StochasticTerrain (Add Pass)': Couldn't open include file 'Packages/com.unity.render-pipelines.universal/ShaderLibrary/DBuffer.hlsl'. at Assets/StochasticTerrainPasses.hlsl

**Comment by JuniorDjjr** [comment]
Which Unity version? I didn't test on 2022 yet. Or URP version.

**Comment by tfalmeida91** [comment]
> Which Unity version? I didn't test on 2022 yet. Or URP version.

I am so sorry, my stupidity got the better of me, I tried these assets on an old project I use to test out things before actually implementing them, and it was running on an older version of unity, not supported by this asset

I updated the version to 2021.2.13f1 and now it works perfectly ^_^!
